# Generated by Django 5.2.8 on 2025-11-22 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('building_number', models.CharField(default='A60', max_length=10)),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Jewelry', 'Jewelry'), ('Clothing', 'Clothing'), ('Bags', 'Bags'), ('Keys', 'Keys'), ('Documents', 'Documents'), ('Pets', 'Pets'), ('Sports Equipment', 'Sports Equipment'), ('Other', 'Other')], max_length=50)),
                ('location_lost', models.CharField(choices=[('CCSIT Building A60', 'CCSIT Building A60'), ('CCSIT Building A61', 'CCSIT Building A61')], max_length=50)),
                ('date_lost', models.DateField()),
                ('status', models.CharField(choices=[('not_found', 'Not Found'), ('found', 'Found')], default='not_found', max_length=20)),
                ('college', models.CharField(blank=True, default='CCIS', max_length=50)),
                ('security_question', models.CharField(max_length=255)),
                ('security_answer', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_images/')),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClaimVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimer_name', models.CharField(max_length=100)),
                ('claimer_email', models.EmailField(max_length=254)),
                ('claimer_answer', models.CharField(max_length=255)),
                ('verification_status', models.CharField(choices=[('verified', 'Verified'), ('rejected', 'Rejected')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='lostandfound.lostitem')),
            ],
        ),
    ]
